In [1]:
import pandas as pd
from tqdm import tqdm
from pmdarima.arima import auto_arima

In [2]:
data = pd.read_pickle('../data/df6.pkl')
#Todos los contadores
todos_los_contadores = data['ID'].unique()
todos_los_contadores

array([   0,    1,    2, ..., 2748, 2749, 2756], dtype=int64)

In [3]:
data_sin_outliers = pd.read_pickle('../data/dataset_sin_outliers.pkl')

In [4]:
#1ºResetear el indice date como variable (el df que se mete no tiene date como variable)
dataset_a_estudiar = data_sin_outliers.reset_index()
#2ºFiltro por periodo para hacer ARIMA
dataset_a_estudiar = dataset_a_estudiar[dataset_a_estudiar['DATE'] > '2019-10-31']
#3ºUna vez se tiene el filtro de fecha, DATE pasa de nuevo a index
dataset_a_estudiar.set_index('DATE', inplace = True)
dataset_a_estudiar

,DELTA_0,DELTA_1,DELTA_2,DELTA_3,DELTA_4,DELTA_5,DELTA_6,DELTA_7,DELTA_8,DELTA_9,...,DELTA_2739,DELTA_2742,DELTA_2743,DELTA_2744,DELTA_2745,DELTA_2746,DELTA_2747,DELTA_2748,DELTA_2749,DELTA_2756
DATE,,,,,,,,,,,,,,,,,,,,,
2019-11-01,502.0,0.000000,1.0,531.0,411.85,0.0,233.0,228.0,0.000000,265.0,...,15.0,202.396176,407.622437,407.622437,612.383518,582.933333,407.622437,435.831081,116.787879,407.622437
2019-11-02,331.0,11.690411,1.0,468.0,343.22,0.0,211.0,108.0,0.000000,236.0,...,15.0,202.396176,380.309537,380.309537,612.383518,582.933333,380.309537,435.831081,116.787879,380.309537
2019-11-03,307.0,0.000000,16.0,411.0,367.78,0.0,151.0,308.0,0.000000,162.0,...,15.0,202.396176,423.227243,423.227243,612.383518,582.933333,423.227243,435.831081,116.787879,423.227243
2019-11-04,272.0,20.000000,23.0,350.0,276.00,0.0,258.0,95.0,3.000000,95.0,...,15.0,202.396176,582.274939,582.274939,612.383518,582.933333,582.274939,435.831081,116.787879,582.274939
2019-11-05,289.0,6.000000,27.0,407.0,298.56,0.0,183.0,125.0,0.000000,246.0,...,15.0,202.396176,513.808989,513.808989,612.383518,582.933333,513.808989,435.831081,116.787879,513.808989
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-27,213.0,4.000000,39.0,289.0,263.06,0.0,204.0,118.0,7.603151,149.0,...,15.0,205.637255,414.904301,414.904301,614.969444,582.933333,414.904301,435.831081,116.787879,414.904301
2020-01-28,232.0,1.000000,40.0,380.0,303.94,0.0,169.0,135.0,7.603151,166.0,...,15.0,205.637255,411.301918,411.301918,614.969444,582.933333,411.301918,435.831081,116.787879,411.301918
2020-01-29,403.0,2.000000,45.0,404.0,421.00,0.0,195.0,77.0,7.603151,101.0,...,15.0,205.637255,418.423941,418.423941,614.969444,582.933333,418.423941,435.831081,116.787879,418.423941
2020-01-30,425.0,10.000000,27.0,339.0,420.00,0.0,152.0,39.0,0.000000,122.0,...,15.0,205.637255,400.926486,400.926486,614.969444,582.933333,400.926486,435.831081,116.787879,400.926486
2020-01-31,255.0,11.690411,59.0,391.0,254.00,0.0,210.0,38.0,7.603151,98.0,...,15.0,205.637255,416.842104,416.842104,614.969444,582.933333,416.842104,435.831081,116.787879,416.842104

In [59]:
#Todas las predicciones en un dataframe de 14 filas (2 ultimas semanas de test)
#para almacenar toda la informacion de los ARIMAs
dataframe_predicciones = data_sin_outliers[['DELTA_0', 'DELTA_1']] #Proceso "tosco"
dataframe_predicciones = dataframe_predicciones.drop(['DELTA_0', 'DELTA_1'], axis=1) #Proceso "tosco"
dataframe_predicciones = dataframe_predicciones[-14:] #Proceso "tosco"
dataframe_predicciones

Empty DataFrame
Columns: []
Index: [2020-01-18 00:00:00, 2020-01-19 00:00:00, 2020-01-20 00:00:00, 2020-01-21 00:00:00, 2020-01-22 00:00:00, 2020-01-23 00:00:00, 2020-01-24 00:00:00, 2020-01-25 00:00:00, 2020-01-26 00:00:00, 2020-01-27 00:00:00, 2020-01-28 00:00:00, 2020-01-29 00:00:00, 2020-01-30 00:00:00, 2020-01-31 00:00:00]

In [ ]:
#Se itera por cada contador
for contador in tqdm(data['ID'].unique()):
  
    #1ºSe aisla el contador que se desea estudiar
    contador_a_estudiar = dataset_a_estudiar[f'DELTA_{contador}']

    #2ºUn modelo por contador
    train = contador_a_estudiar[:(92-14)]
    test = contador_a_estudiar[-14:]
    arima_model = auto_arima(train, 
                        start_p=0, 
                        d=1, 
                        start_q=0, 
                        max_p=7, 
                        max_d=7, 
                        max_q=7, 
                        start_P=0, 
                        D=1, 
                        start_Q=0, 
                        max_P=7, 
                        max_D=7, 
                        max_Q=7, 
                        m=12, 
                        seasonal=True, 
                        error_action='warn', 
                        trace=True, 
                        supress_warnings=True, 
                        stepwise=True, 
                        random_state=2517, 
                        n_fits=100)
    prediction = pd.DataFrame(arima_model.predict(n_periods = 14), index = test.index)

    #3ºLas predicciones por contador se pasan a una nueva columna del dataframe de return
    dataframe_predicciones[f'predict_cont_{contador}'] = prediction

In [21]:
data2 = pd.read_pickle('../data/arima_hasta_2400.pkl')
data2

,predict_cont_0,predict_cont_1,predict_cont_2,predict_cont_3,predict_cont_4,predict_cont_5,predict_cont_6,predict_cont_7,predict_cont_8,predict_cont_9,...,predict_cont_2394,predict_cont_2395,predict_cont_2396,predict_cont_2397,predict_cont_2398,predict_cont_2399,predict_cont_2400,predict_cont_2401,predict_cont_2402,predict_cont_2403
DATE,,,,,,,,,,,,,,,,,,,,,
2020-01-18,346.374206,6.737183,38.908300,471.775279,103.962025,0.0,106.650175,189.977627,0.918430,45.539666,...,88.037428,59.304236,477.150813,194.464788,536.987849,31.550925,195.586349,473.618992,409.651935,286.196387
2020-01-19,265.689752,4.486606,38.098945,277.778903,196.063992,0.0,215.606830,29.544437,2.777290,-8.809393,...,24.635365,110.333679,477.150813,194.524562,333.343301,36.490691,125.879659,290.528194,323.392077,710.130850
2020-01-20,365.570080,3.018055,36.019619,340.531200,318.806578,0.0,238.811720,59.624671,3.047814,-22.364962,...,19.842772,52.858066,477.150813,258.454059,361.625924,36.946285,114.458259,388.305114,397.676410,710.130850
2020-01-21,356.358093,7.385677,46.344488,317.720288,194.849129,0.0,235.491911,53.772386,4.099232,50.264201,...,8.196145,39.282590,333.699551,114.204694,319.684274,56.231261,95.354147,451.648755,383.671998,710.130850
2020-01-22,270.061836,9.130274,38.059881,423.156304,156.833658,0.0,178.171196,90.586020,1.467708,13.212599,...,18.275754,47.497101,490.703898,156.150957,336.429873,51.492897,81.151933,396.599360,379.560444,710.130850
2020-01-23,248.713237,6.268221,34.178412,383.429773,197.735287,0.0,192.176087,37.618001,3.926902,3.790854,...,70.913828,137.937924,490.703898,316.102110,444.408143,65.027877,102.248788,363.045414,385.184302,710.130850
2020-01-24,262.815579,3.998136,35.742352,337.484160,199.748881,0.0,250.853196,152.980928,0.366924,14.585437,...,88.136264,81.614922,490.703898,273.575133,406.820928,40.339557,112.969150,397.964359,359.435255,710.130850
2020-01-25,272.182178,1.428094,33.129320,315.081118,153.787205,0.0,229.692632,36.875748,3.897690,-3.367888,...,119.142856,33.437867,487.776483,145.788833,436.686120,52.181026,116.604660,355.550494,345.390330,380.094844
2020-01-26,310.006146,1.135997,44.795888,314.761817,198.574567,0.0,193.745684,75.919128,1.550685,-26.520233,...,138.854927,53.809722,501.350664,188.297336,406.969557,49.609766,136.925202,265.737626,349.140028,608.728237
2020-01-27,186.522353,3.785206,42.453818,279.793260,163.981628,0.0,224.481068,77.638406,3.919958,-26.006581,...,92.146111,-1.933318,595.866219,165.755253,254.805493,36.814003,111.323494,347.069726,390.582172,608.728237
2020-01-28,449.135420,3.398554,35.992391,421.501478,225.470199,0.0,176.626253,57.506598,0.380990,-38.528878,...,155.728147,63.363560,390.050981,160.619485,300.810475,48.948588,143.405392,260.309405,318.925315,608.728237
2020-01-29,332.580418,1.693673,39.297668,309.376849,162.353479,0.0,265.993791,36.604406,1.553311,22.868652,...,57.505243,64.295795,718.201204,187.597311,194.946738,51.636300,99.363548,445.528604,423.284685,608.728237
2020-01-30,341.334940,6.906993,41.365983,493.024374,79.113764,0.0,151.490076,188.006601,0.522876,-2.599295,...,56.609390,49.974407,734.494137,159.611631,226.610106,29.763339,164.738615,308.366609,411.319169,456.808845
2020-01-31,354.542881,4.663789,40.556629,373.672436,149.529496,0.0,197.862841,27.573411,3.730542,-45.282053,...,39.289361,95.547844,734.494137,183.165958,213.977427,67.897130,119.248562,240.915407,341.926476,769.505279

In [22]:
results_df = data2.T
results_df.columns = [['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7',
                       'Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']]
results_df['Semana_1'] = results_df[['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7']].sum(axis=1)
results_df['Semana_2'] = results_df[['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']].sum(axis=1)
results_df.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)
results_df

C:\Users\Manuel\AppData\Local\Temp/ipykernel_540/2541943868.py:6: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  results_df.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)

,Dia_1,Dia_2,Dia_3,Dia_4,Dia_5,Dia_6,Dia_7,Semana_1,Semana_2
predict_cont_0,346.374206,265.689752,365.570080,356.358093,270.061836,248.713237,262.815579,2115.582782,2246.304335
predict_cont_1,6.737183,4.486606,3.018055,7.385677,9.130274,6.268221,3.998136,41.024152,23.012305
predict_cont_2,38.908300,38.098945,36.019619,46.344488,38.059881,34.178412,35.742352,267.351996,277.591698
predict_cont_3,471.775279,277.778903,340.531200,317.720288,423.156304,383.429773,337.484160,2551.875906,2507.211332
predict_cont_4,103.962025,196.063992,318.806578,194.849129,156.833658,197.735287,199.748881,1367.999550,1132.810339
...,...,...,...,...,...,...,...,...,...
predict_cont_2399,31.550925,36.490691,36.946285,56.231261,51.492897,65.027877,40.339557,318.079493,336.850152
predict_cont_2400,195.586349,125.879659,114.458259,95.354147,81.151933,102.248788,112.969150,827.648284,891.609473
predict_cont_2401,473.618992,290.528194,388.305114,451.648755,396.599360,363.045414,397.964359,2761.710190,2223.477871
predict_cont_2402,409.651935,323.392077,397.676410,383.671998,379.560444,385.184302,359.435255,2638.572419,2580.568175
predict_cont_2403,286.196387,710.130850,710.130850,710.130850,710.130850,710.130850,710.130850,4546.981485,4041.321916

In [39]:
test2 = dataset_a_estudiar[-14:]
test2

,DELTA_0,DELTA_1,DELTA_2,DELTA_3,DELTA_4,DELTA_5,DELTA_6,DELTA_7,DELTA_8,DELTA_9,...,DELTA_2739,DELTA_2742,DELTA_2743,DELTA_2744,DELTA_2745,DELTA_2746,DELTA_2747,DELTA_2748,DELTA_2749,DELTA_2756
DATE,,,,,,,,,,,,,,,,,,,,,
2020-01-18,421.0,0.000000,28.0,485.0,365.00,0.0,149.0,144.052055,0.000000,29.0,...,15.0,205.637255,438.500082,438.500082,614.969444,582.933333,438.500082,435.831081,116.787879,438.500082
2020-01-19,273.0,11.690411,33.0,394.0,387.00,0.0,190.0,255.000000,0.000000,234.0,...,15.0,205.637255,363.889917,363.889917,614.969444,582.933333,363.889917,435.831081,116.787879,363.889917
2020-01-20,306.0,14.000000,48.0,237.0,370.00,0.0,170.0,76.000000,0.000000,80.0,...,15.0,205.637255,444.643897,444.643897,614.969444,582.933333,444.643897,435.831081,116.787879,444.643897
2020-01-21,292.0,3.000000,35.0,297.0,293.00,0.0,132.0,30.000000,5.000000,109.0,...,15.0,205.637255,390.535651,390.535651,614.969444,582.933333,390.535651,435.831081,116.787879,390.535651
2020-01-22,460.0,0.000000,33.0,312.0,287.00,0.0,228.0,202.000000,0.000000,128.0,...,15.0,205.637255,428.618820,428.618820,614.969444,582.933333,428.618820,435.831081,116.787879,428.618820
2020-01-23,331.0,3.000000,20.0,321.0,361.00,0.0,210.0,92.000000,0.000000,315.0,...,15.0,205.637255,409.824931,409.824931,614.969444,582.933333,409.824931,435.831081,116.787879,409.824931
2020-01-24,368.0,5.670000,37.0,439.0,203.00,0.0,161.0,28.000000,7.603151,409.0,...,15.0,205.637255,408.652628,408.652628,614.969444,582.933333,408.652628,435.831081,116.787879,408.652628
2020-01-25,390.0,1.330000,30.0,639.0,272.00,0.0,131.0,27.000000,0.000000,187.0,...,15.0,205.637255,365.864302,365.864302,614.969444,582.933333,365.864302,435.831081,116.787879,365.864302
2020-01-26,304.0,3.000000,32.0,350.0,282.00,0.0,211.0,328.000000,0.000000,88.0,...,15.0,205.637255,384.467399,384.467399,614.969444,582.933333,384.467399,435.831081,116.787879,384.467399
2020-01-27,213.0,4.000000,39.0,289.0,263.06,0.0,204.0,118.000000,7.603151,149.0,...,15.0,205.637255,414.904301,414.904301,614.969444,582.933333,414.904301,435.831081,116.787879,414.904301
2020-01-28,232.0,1.000000,40.0,380.0,303.94,0.0,169.0,135.000000,7.603151,166.0,...,15.0,205.637255,411.301918,411.301918,614.969444,582.933333,411.301918,435.831081,116.787879,411.301918
2020-01-29,403.0,2.000000,45.0,404.0,421.00,0.0,195.0,77.000000,7.603151,101.0,...,15.0,205.637255,418.423941,418.423941,614.969444,582.933333,418.423941,435.831081,116.787879,418.423941
2020-01-30,425.0,10.000000,27.0,339.0,420.00,0.0,152.0,39.000000,0.000000,122.0,...,15.0,205.637255,400.926486,400.926486,614.969444,582.933333,400.926486,435.831081,116.787879,400.926486
2020-01-31,255.0,11.690411,59.0,391.0,254.00,0.0,210.0,38.000000,7.603151,98.0,...,15.0,205.637255,416.842104,416.842104,614.969444,582.933333,416.842104,435.831081,116.787879,416.842104

In [40]:
test_3 = test2.T
test_3.columns = [['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7',
                       'Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']]
test_3['Semana_1'] = test_3[['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7']].sum(axis=1)
test_3['Semana_2'] = test_3[['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']].sum(axis=1)
test_3.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)
test_3

C:\Users\Manuel\AppData\Local\Temp/ipykernel_20664/172659562.py:6: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  test_3.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)

,Dia_1,Dia_2,Dia_3,Dia_4,Dia_5,Dia_6,Dia_7,Semana_1,Semana_2
DELTA_0,421.000000,273.000000,306.000000,292.000000,460.000000,331.000000,368.000000,2451.000000,2222.000000
DELTA_1,0.000000,11.690411,14.000000,3.000000,0.000000,3.000000,5.670000,37.360411,33.020411
DELTA_2,28.000000,33.000000,48.000000,35.000000,33.000000,20.000000,37.000000,234.000000,272.000000
DELTA_3,485.000000,394.000000,237.000000,297.000000,312.000000,321.000000,439.000000,2485.000000,2792.000000
DELTA_4,365.000000,387.000000,370.000000,293.000000,287.000000,361.000000,203.000000,2266.000000,2216.000000
...,...,...,...,...,...,...,...,...,...
DELTA_2746,582.933333,582.933333,582.933333,582.933333,582.933333,582.933333,582.933333,4080.533333,4080.533333
DELTA_2747,438.500082,363.889917,444.643897,390.535651,428.618820,409.824931,408.652628,2884.665926,2812.730452
DELTA_2748,435.831081,435.831081,435.831081,435.831081,435.831081,435.831081,435.831081,3050.817568,3050.817568
DELTA_2749,116.787879,116.787879,116.787879,116.787879,116.787879,116.787879,116.787879,817.515152,817.515152
DELTA_2756,438.500082,363.889917,444.643897,390.535651,428.618820,409.824931,408.652628,2884.665926,2812.730452

In [42]:
test_3 = test_3.head(2640)
test_3

,Dia_1,Dia_2,Dia_3,Dia_4,Dia_5,Dia_6,Dia_7,Semana_1,Semana_2
DELTA_0,421.000000,273.000000,306.000000,292.000000,460.000000,331.000000,368.000000,2451.000000,2222.000000
DELTA_1,0.000000,11.690411,14.000000,3.000000,0.000000,3.000000,5.670000,37.360411,33.020411
DELTA_2,28.000000,33.000000,48.000000,35.000000,33.000000,20.000000,37.000000,234.000000,272.000000
DELTA_3,485.000000,394.000000,237.000000,297.000000,312.000000,321.000000,439.000000,2485.000000,2792.000000
DELTA_4,365.000000,387.000000,370.000000,293.000000,287.000000,361.000000,203.000000,2266.000000,2216.000000
...,...,...,...,...,...,...,...,...,...
DELTA_2635,1239.557142,1239.557142,1239.557142,1239.557142,1239.557142,1239.557142,1239.557142,8676.899992,8676.899992
DELTA_2636,47.353425,47.353425,47.353425,47.353425,47.353425,47.353425,47.353425,331.473973,334.767123
DELTA_2637,229.934783,223.181418,223.181418,223.181418,223.181418,223.181418,223.181418,1569.023288,1582.530018
DELTA_2638,29.609375,34.000000,1.000000,0.000000,1.000000,13.000000,1.000000,79.609375,51.000000
DELTA_2639,33.919178,33.919178,33.919178,33.919178,35.291667,33.919178,33.919178,238.806735,242.924201

In [43]:
def compute_error(pred, real):
    daily_rmses = []
    for i in range(7):
        daily_rmses.append((((real.iloc[:,i] - pred.iloc[:,i])**2/len(real.iloc[:,i])).sum())**(1/2))
    rmse_1 = sum(daily_rmses)/7
    
    first_week_pred_sum = pred.iloc[:,7].sum()
    second_week_pred_sum = pred.iloc[:,8].sum()
    first_week_real_sum = real.iloc[:,7].sum()
    second_week_real_sum = real.iloc[:,8].sum()
    
    first_week_rmse = (((first_week_real_sum - first_week_pred_sum)**2)/len(real.iloc[:,7]))**(1/2)
    second_week_rmse = (((second_week_real_sum - second_week_pred_sum)**2)/len(real.iloc[:,8]))**(1/2)
    rmse_2 = (first_week_rmse + second_week_rmse)/2
    
    return (rmse_1 + rmse_2)/2

In [29]:
compute_error(results_df, test_3)

7855.446483657563

## Últimos 300 contadores.

In [ ]:
todos_los_contadores = data['ID'].unique()
todos_los_contadores

In [57]:
contadores_filtrado = []
for contador in todos_los_contadores:
    if contador >= 2641:
        contadores_filtrado.append(contador)

In [58]:
contadores_filtrado

[2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2648,
 2649,
 2650,
 2651,
 2652,
 2653,
 2654,
 2655,
 2656,
 2657,
 2658,
 2659,
 2660,
 2661,
 2662,
 2663,
 2664,
 2665,
 2666,
 2667,
 2668,
 2669,
 2670,
 2671,
 2672,
 2673,
 2674,
 2675,
 2676,
 2677,
 2678,
 2679,
 2680,
 2681,
 2682,
 2683,
 2684,
 2685,
 2686,
 2687,
 2688,
 2689,
 2690,
 2691,
 2692,
 2693,
 2694,
 2695,
 2696,
 2697,
 2698,
 2699,
 2700,
 2701,
 2702,
 2703,
 2704,
 2705,
 2706,
 2707,
 2708,
 2709,
 2710,
 2711,
 2712,
 2713,
 2714,
 2715,
 2716,
 2717,
 2718,
 2719,
 2720,
 2721,
 2722,
 2723,
 2724,
 2725,
 2727,
 2728,
 2729,
 2730,
 2731,
 2732,
 2733,
 2734,
 2735,
 2736,
 2737,
 2739,
 2742,
 2743,
 2744,
 2745,
 2746,
 2747,
 2748,
 2749,
 2756]

In [ ]:
#Se itera por cada contador
for contador in tqdm(contadores_filtrado):
  
    #1ºSe aisla el contador que se desea estudiar
    contador_a_estudiar = dataset_a_estudiar[f'DELTA_{contador}']

    #2ºUn modelo por contador
    train = contador_a_estudiar[:(92-14)]
    test = contador_a_estudiar[-14:]
    arima_model = auto_arima(train, 
                        start_p=0, 
                        d=1, 
                        start_q=0, 
                        max_p=7, 
                        max_d=7, 
                        max_q=7, 
                        start_P=0, 
                        D=1, 
                        start_Q=0, 
                        max_P=7, 
                        max_D=7, 
                        max_Q=7, 
                        m=12, 
                        seasonal=True, 
                        error_action='warn', 
                        trace=True, 
                        supress_warnings=True, 
                        stepwise=True, 
                        random_state=2517, 
                        n_fits=100)
    prediction = pd.DataFrame(arima_model.predict(n_periods = 14), index = test.index)

    print(f'===================== Contador {contador} acabado =====================')
    #3ºLas predicciones por contador se pasan a una nueva columna del dataframe de return
    dataframe_predicciones[f'predict_cont_{contador}'] = prediction

In [61]:
dataframe_predicciones

,predict_cont_2641,predict_cont_2642,predict_cont_2643,predict_cont_2644,predict_cont_2645,predict_cont_2646,predict_cont_2647,predict_cont_2648,predict_cont_2649,predict_cont_2650,predict_cont_2651
DATE,,,,,,,,,,,
2020-01-18,34.294746,22.326413,111.017002,25.595316,0.341143,182.696113,18.534293,48.570384,418.837215,74.526782,190.987987
2020-01-19,35.849773,22.326413,106.035536,28.172795,0.341143,182.704574,18.534293,47.056797,418.837215,80.384521,191.254050
2020-01-20,35.849773,22.326413,106.035536,25.072034,1.493301,182.691414,18.534293,42.028531,412.632763,72.938662,181.997720
2020-01-21,36.672400,22.326413,106.035536,25.072034,1.011227,182.691377,18.534293,34.480013,412.632763,74.775173,181.282543
2020-01-22,38.249495,22.326413,102.931865,24.837207,1.219303,205.885241,18.715769,38.242351,412.632763,75.915332,189.930254
2020-01-23,35.117372,22.326413,102.931865,24.673478,1.266528,182.683355,18.715769,38.242104,412.632763,76.109732,192.803284
2020-01-24,35.117372,22.326413,102.931865,24.650932,0.826086,182.683745,18.715770,39.049421,412.632763,85.888952,190.901711
2020-01-25,35.117372,22.326413,102.931865,24.736584,1.936079,182.683745,18.715770,31.944148,412.632763,79.765797,201.887766
2020-01-26,36.694467,22.326413,102.931865,25.402958,1.268224,182.683745,18.715770,41.716543,412.632763,79.393861,190.799527
2020-01-27,36.694467,22.326413,102.931865,28.208177,0.686596,182.683745,18.579007,45.011007,412.632763,79.091959,185.245309
2020-01-28,36.694467,22.326413,102.931865,25.402958,0.358113,182.691969,18.579007,43.610180,412.632763,79.400238,183.083552
2020-01-29,35.117372,22.326413,107.913331,27.475347,0.568361,205.884373,18.579007,43.435127,412.632763,77.473025,176.269982
2020-01-30,35.136917,22.326413,107.913331,25.720087,0.336618,205.876116,18.397531,47.201993,412.632763,74.622974,190.223552
2020-01-31,35.117181,22.326413,106.841461,28.297566,0.336618,205.881111,18.397531,45.688406,412.632763,79.183933,200.088419

In [14]:
dataframe_predicciones.to_pickle('../data/predicciones_314_primeros.pkl')

In [25]:
dataframe_predicciones.to_pickle('../data/predicciones_2404_2639.pkl')

In [ ]:
dataframe_predicciones.to_pickle('../data/predicciones_2441_2651.pkl')

In [37]:
data3 = pd.read_pickle('../data/arima_hasta_2400.pkl')
results_df = data3.T
results_df.columns = [['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7',
                       'Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']]
results_df['Semana_1'] = results_df[['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7']].sum(axis=1)
results_df['Semana_2'] = results_df[['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']].sum(axis=1)
results_df.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)
results_df

data4 = pd.read_pickle('../data/predicciones_2404_2639.pkl')
results_df2 = data4.T
results_df2.columns = [['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7',
                       'Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']]
results_df2['Semana_1'] = results_df2[['Dia_1','Dia_2','Dia_3','Dia_4','Dia_5','Dia_6','Dia_7']].sum(axis=1)
results_df2['Semana_2'] = results_df2[['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14']].sum(axis=1)
results_df2.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)
results_df2

results = pd.concat([results_df, results_df2])

C:\Users\Manuel\AppData\Local\Temp/ipykernel_20664/677467402.py:7: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  results_df.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)
C:\Users\Manuel\AppData\Local\Temp/ipykernel_20664/677467402.py:16: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  results_df2.drop(['Dia_8','Dia_9','Dia_10','Dia_11','Dia_12','Dia_13','Dia_14'], axis=1, inplace=True)

In [44]:
compute_error(results, test_3)

2357.1332125844756

155.08

False