In [14]:
import pandas as pd

In [15]:
datos = pd.read_csv('enriquecidos-004.pkl')
datos

,Unnamed: 0,ID,DATE,DELTA,READING,PRECIPITATIONS,MIN_TEMP,MEAN_TEMP,MAX_TEMP,SUN,WEEK_DAY,IS_WEEKEND,sin_WEEK_DAY,cos_WEEK_DAY,IS_PUBLIC_HOLIDAY
0,0,0,2019-02-01,243.0,331953.0,0.0,16.5,17.6,18.7,7.1,4,0,-0.433884,-0.900969,0
1,1,0,2019-02-02,236.0,332189.0,0.0,9.8,13.4,17.1,6.1,5,1,-0.974928,-0.222521,0
2,2,0,2019-02-03,335.0,332524.0,0.0,7.7,10.6,13.6,9.3,6,1,-0.781831,0.623490,0
3,3,0,2019-02-04,252.0,332776.0,0.0,4.1,10.6,17.2,9.3,0,0,0.000000,1.000000,0
4,4,0,2019-02-05,220.0,332996.0,0.0,7.5,14.6,21.6,9.2,1,0,0.781831,0.623490,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890832,890832,2748,2019-08-03,313.0,406953.0,0.0,22.5,26.2,29.9,11.4,5,1,-0.974928,-0.222521,0
890833,890833,2748,2019-09-14,8.0,422515.0,0.0,17.5,21.6,25.8,2.6,5,1,-0.974928,-0.222521,0
890834,890834,2749,2019-08-06,0.0,156799.0,0.0,25.5,28.2,31.0,7.6,1,0,0.781831,0.623490,0
890835,890835,2749,2019-10-11,2.0,164507.0,0.0,20.5,23.5,26.5,8.6,4,0,-0.433884,-0.900969,0
890836,890836,2756,2019-04-06,12.0,349770.0,1.1,9.5,13.5,17.5,5.9,5,1,-0.974928,-0.222521,0

In [3]:
datos.columns

Index(['Unnamed: 0', 'ID', 'DATE', 'DELTA', 'READING', 'PRECIPITATIONS',
       'MIN_TEMP', 'MEAN_TEMP', 'MAX_TEMP', 'SUN', 'WEEK_DAY', 'IS_WEEKEND',
       'sin_WEEK_DAY', 'cos_WEEK_DAY', 'IS_PUBLIC_HOLIDAY'],
      dtype='object')

In [21]:
datos.drop(columns = ['Unnamed: 0', 'DATE'], inplace = True)

In [22]:
groups = datos.groupby('ID').sum()
groups['TotalCons'] = groups['DELTA']
groups = groups['TotalCons']

In [23]:
groups2 = datos.groupby('ID').var()
groups2['Variance'] = groups2['DELTA']
groups2 = groups2['Variance']

In [26]:
datos = pd.merge(datos, groups, left_on='ID', right_on = 'ID')
datos = pd.merge(datos, groups2, left_on='ID', right_on = 'ID')
datos.astype({"ID":'category'})

,ID,DELTA,READING,PRECIPITATIONS,MIN_TEMP,MEAN_TEMP,MAX_TEMP,SUN,WEEK_DAY,IS_WEEKEND,sin_WEEK_DAY,cos_WEEK_DAY,IS_PUBLIC_HOLIDAY,TotalCons_x,Variance_x,TotalCons_y,Variance_y,TotalCons,Variance
0,0,243.0,331953.0,0.0,16.5,17.6,18.7,7.1,4,0,-0.433884,-0.900969,0,103224.5,11451.125585,103224.5,11451.125585,103224.5,11451.125585
1,0,236.0,332189.0,0.0,9.8,13.4,17.1,6.1,5,1,-0.974928,-0.222521,0,103224.5,11451.125585,103224.5,11451.125585,103224.5,11451.125585
2,0,335.0,332524.0,0.0,7.7,10.6,13.6,9.3,6,1,-0.781831,0.623490,0,103224.5,11451.125585,103224.5,11451.125585,103224.5,11451.125585
3,0,252.0,332776.0,0.0,4.1,10.6,17.2,9.3,0,0,0.000000,1.000000,0,103224.5,11451.125585,103224.5,11451.125585,103224.5,11451.125585
4,0,220.0,332996.0,0.0,7.5,14.6,21.6,9.2,1,0,0.781831,0.623490,0,103224.5,11451.125585,103224.5,11451.125585,103224.5,11451.125585
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890832,2748,313.0,406953.0,0.0,22.5,26.2,29.9,11.4,5,1,-0.974928,-0.222521,0,334.0,23437.666667,334.0,23437.666667,334.0,23437.666667
890833,2748,8.0,422515.0,0.0,17.5,21.6,25.8,2.6,5,1,-0.974928,-0.222521,0,334.0,23437.666667,334.0,23437.666667,334.0,23437.666667
890834,2749,0.0,156799.0,0.0,25.5,28.2,31.0,7.6,1,0,0.781831,0.623490,0,2.0,2.000000,2.0,2.000000,2.0,2.000000
890835,2749,2.0,164507.0,0.0,20.5,23.5,26.5,8.6,4,0,-0.433884,-0.900969,0,2.0,2.000000,2.0,2.000000,2.0,2.000000
890836,2756,12.0,349770.0,1.1,9.5,13.5,17.5,5.9,5,1,-0.974928,-0.222521,0,12.0,NaN,12.0,NaN,12.0,NaN

In [27]:
from pycaret.regression import *
datos['DELTA'] = datos['DELTA'].apply(lambda x: float(x))
init = setup(datos, target = 'DELTA', train_size = 0.9, use_gpu = True, n_jobs = 16)

In [13]:
best = compare_models(budget_time = 100)

In [28]:
best = compare_models(budget_time = 100)