Como primera baseline predecimos para cada contador y cada día el mismo consumo de agua que tuvo ese mismo contador ese mismo día del año pero el año pasado.

Vamos a utilizar como test la última semana de Enero

In [1]:
import pandas as pd

data = pd.read_csv('../data/enriquecidos-003.csv')
data.head()

,Unnamed: 0,DATE,ID,READINGINTEGER,READINGTHOUSANDTH,DELTAINTEGER,DELTATHOUSANDTH,YEAR,MONTH,DAY,...,YEAR_DAY,sin_WEEK_DAY,cos_WEEK_DAY,sin_YEAR_DAY,cos_YEAR_DAY,MIN_TEMP,MEAN_TEMP,MAX_TEMP,SUN,PRECIPITATIONS
0,0,2019-02-01,0,7963359,0.0,243,0.0,2019.0,2.0,1.0,...,32,-0.433884,-0.900969,0.523416,0.852078,16.5,17.6,18.7,7.1,0.0
1,1,2019-02-01,1,139882,0.0,8,0.0,2019.0,2.0,1.0,...,32,-0.433884,-0.900969,0.523416,0.852078,16.5,17.6,18.7,7.1,0.0
2,2,2019-02-01,2,190824,0.0,0,0.0,2019.0,2.0,1.0,...,32,-0.433884,-0.900969,0.523416,0.852078,16.5,17.6,18.7,7.1,0.0
3,3,2019-02-01,3,3611828,0.0,492,0.0,2019.0,2.0,1.0,...,32,-0.433884,-0.900969,0.523416,0.852078,16.5,17.6,18.7,7.1,0.0
4,4,2019-02-01,4,2723035,0.0,247,56.0,2019.0,2.0,1.0,...,32,-0.433884,-0.900969,0.523416,0.852078,16.5,17.6,18.7,7.1,0.0

In [2]:
from datetime import datetime

def str2date2(string):
    return datetime.strptime(string, '%Y-%m-%d')

In [ ]:
def mse(real, prediction):

In [4]:
january_last_week = [str2date2(i) for i in ["2020-1-25","2020-1-26","2020-1-27","2020-1-28","2020-1-29",
                                                       "2020-1-30","2020-1-31"]]
real = data.filter(data['DATE'] in january_last_week)
real.shape

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().